name: Lint
permissions: {}

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

env:
  CI: true
  FORCE_COLOR: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup pnpm
        uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          cache: pnpm
          node-version: 24.14.0

      - name: Install dependencies
        run: pnpm i

      - name: Lint - Spelling
        run: pnpm run lint:spelling

      - name: Lint - Formatting
        run: pnpm run lint:formatting
