name: Release
permissions: {}

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

env:
  CI: true
  FORCE_COLOR: true

jobs:
  release:
    name: Release
    if: ${{ github.repository_owner == 'ArmandPhilippot' }}
    permissions:
      contents: write # to create release (changesets/action)
      issues: write # to post issue comments (changesets/action)
      pull-requests: write # to create pull request (changesets/action)
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - name: Install Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24.19.0
          package-manager-cache: false

      - name: Install dependencies
        run: pnpm i

      - name: Create Release Pull Request
        uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1.9.0
        with:
          version: pnpm ci:version
          commit: "chore: new release"
          title: "chore: new release candidate"
          publish: pnpm ci:release
        env:
          # Needs access to push to main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
